name: Deploy Databricks Dashboard 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
      DATABRICKS_AUTH_TYPE: oauth-m2m

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Databricks CLI
        uses: databricks/setup-cli@main

      - name: Valider le bundle
        run: databricks bundle validate -t dev