name: Deploy Databricks Dashboard

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
      - name: Installer Databricks dans le CLI
        uses: databricks/setup-cli@main   

        